describe('My Blackbox CRUD Supplier Test', () => {
    it('Admin can Read Data', () => {
        cy.visit("http://127.0.0.1:8000/login") 
        cy.get(':nth-child(2) > .form-control').type("admin2@gmail.com")
        cy.get(':nth-child(3) > .form-control').type("adminima")
        cy.get('.btn').click({force: true})
        cy.get(':nth-child(3) > .nav-link > .far').click({force: true})
        cy.get('h2').contains("Data Supplier")
    })
    it('Admin Can Create New Supplier', () => {
        cy.visit("http://127.0.0.1:8000/login") 
        cy.get(':nth-child(2) > .form-control').type("admin2@gmail.com")
        cy.get(':nth-child(3) > .form-control').type("adminima")
        cy.get('.btn').click({force: true})
        cy.get(':nth-child(3) > .nav-link > .far').click({force: true})
        cy.get('h2').contains("Data Supplier")
        cy.get('[href="http://127.0.0.1:8000/createSupplier"]').click({force: true})
        cy.get('h3').contains("Form Tambah Data Supplier")
        cy.get(':nth-child(2) > .form-control').type("Ima Cantik")
        cy.get(':nth-child(3) > .form-control').type("Tarik")
        cy.get(':nth-child(4) > .form-control').type("08123456789")
        cy.get('#myForm > .btn').click({force: true})
    })
    it('Admin can Edit/Update Data', () => {
        cy.visit("http://127.0.0.1:8000/login") 
        cy.get(':nth-child(2) > .form-control').type("admin2@gmail.com")
        cy.get(':nth-child(3) > .form-control').type("adminima")
        cy.get('.btn').click({force: true})
        cy.get(':nth-child(3) > .nav-link > .far').click({force: true})
        cy.get('h2').contains("Data Supplier")
        cy.get('.settings > .material-icons').click({force: true})
        cy.get('h3').contains("Form Edit Data Supplier")
        cy.get(':nth-child(2) > .form-control').type(" Poll")
        cy.get(':nth-child(3) > .form-control').type(", Sidoarjo")
        cy.get(':nth-child(4) > .form-control').type("99")
        cy.get('.float-right > .btn').click({force: true})
    })
    it('Admin can Delete Data', () => {
        cy.visit("http://127.0.0.1:8000/login") 
        cy.get(':nth-child(2) > .form-control').type("admin2@gmail.com")
        cy.get(':nth-child(3) > .form-control').type("adminima")
        cy.get('.btn').click({force: true})
        cy.get(':nth-child(3) > .nav-link > .far').click({force: true})
        cy.get('h2').contains("Data Supplier")
        cy.get('.delete > .material-icons').click({force: true})
    })
  })